"""empty message

Revision ID: 9891712ead4a
Revises: 
Create Date: 2020-08-22 17:15:21.535936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9891712ead4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('images')
    op.drop_table('liquids')
    op.drop_table('categories')
    op.drop_table('order_products')
    op.drop_table('accessories')
    op.drop_table('main_page')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('sale', sa.INTEGER(), nullable=True),
    sa.Column('connection_id', sa.INTEGER(), nullable=False),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_page',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accessories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('color', sa.VARCHAR(length=100), nullable=False),
    sa.Column('connection_id', sa.INTEGER(), nullable=False),
    sa.Column('type_category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id_category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('sale', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_depend', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['order_depend'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquids',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), nullable=False),
    sa.Column('taste', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('salt', sa.INTEGER(), nullable=True),
    sa.Column('vg_to_pg', sa.INTEGER(), nullable=True),
    sa.Column('nicotine', sa.INTEGER(), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sale', sa.INTEGER(), nullable=True),
    sa.Column('connection_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('img_id', sa.INTEGER(), nullable=False),
    sa.Column('depend_id', sa.INTEGER(), nullable=True),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['depend_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('img_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=100), nullable=False),
    sa.Column('mail', sa.VARCHAR(length=100), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=300), nullable=False),
    sa.Column('delivery', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('payment_method', sa.INTEGER(), nullable=False),
    sa.Column('sale', sa.INTEGER(), nullable=False),
    sa.Column('pre_price', sa.INTEGER(), nullable=False),
    sa.Column('final_price', sa.INTEGER(), nullable=False),
    sa.Column('order_time', sa.DATETIME(), nullable=True),
    sa.Column('others', sa.TEXT(), nullable=True),
    sa.Column('products_order_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['products_order_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
