# Generated by Django 3.1 on 2020-09-30 21:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='категории')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('add_time', models.TimeField(default=datetime.datetime(2020, 10, 1, 0, 15, 30, 937435), verbose_name='Время добавления')),
                ('add_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Новое поступление',
                'verbose_name_plural': 'Новые поступления',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('comment', models.TextField()),
                ('event_time', models.TimeField(default=datetime.datetime(2020, 10, 1, 0, 15, 30, 938434), verbose_name='Время добавления')),
                ('event_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('created', models.TimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('pre_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order')),
            ],
        ),
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('title_slug', models.CharField(default='<django.db.models.fields.CharField>', editable=False, max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('brand', models.CharField(default='другие', max_length=255, verbose_name='Бренд')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('add_time', models.TimeField(default=datetime.datetime(2020, 10, 1, 0, 15, 30, 935441), verbose_name='Время добавления')),
                ('add_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Скидка')),
                ('taste', models.CharField(default='другие', max_length=255, verbose_name='Вкус')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Объем')),
                ('salt', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=255, verbose_name='SALT')),
                ('vg_to_pg', models.CharField(max_length=255, null=True, verbose_name='ВГ на ПГ')),
                ('nicotine', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Содержание никотина')),
                ('country', models.CharField(default='другие', max_length=255, verbose_name='Страна производитель')),
                ('paid', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Жидкость',
                'verbose_name_plural': 'Жидкости',
            },
        ),
        migrations.CreateModel(
            name='Crate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('title_slug', models.CharField(default='<django.db.models.fields.CharField>', editable=False, max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('brand', models.CharField(default='другие', max_length=255, verbose_name='Бренд')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('add_time', models.TimeField(default=datetime.datetime(2020, 10, 1, 0, 15, 30, 935441), verbose_name='Время добавления')),
                ('add_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Скидка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Наборы',
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('title_slug', models.CharField(default='<django.db.models.fields.CharField>', editable=False, max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('brand', models.CharField(default='другие', max_length=255, verbose_name='Бренд')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('add_time', models.TimeField(default=datetime.datetime(2020, 10, 1, 0, 15, 30, 935441), verbose_name='Время добавления')),
                ('add_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Скидка')),
                ('color', models.CharField(default='другие', max_length=100)),
                ('type_category', models.CharField(choices=[('MND', 'Мундштуки'), ('CRT', 'Картриджи'), ('NMK', 'Намотки'), ('IS', 'Испарители')], max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
            },
        ),
    ]
