# Generated by Django 3.1 on 2020-09-30 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 0, 16, 0, 562417), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('NMK', 'Намотки'), ('MND', 'Мундштуки'), ('IS', 'Испарители'), ('CRT', 'Картриджи')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crate',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 0, 16, 0, 562417), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 0, 16, 0, 562417), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 0, 16, 0, 565409), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 1, 0, 16, 0, 565409), verbose_name='Время добавления'),
        ),
    ]
