# Generated by Django 3.1 on 2020-09-06 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='brand',
            field=models.CharField(default='другие', max_length=255, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='color',
            field=models.CharField(default='другие', max_length=100),
        ),
        migrations.AddField(
            model_name='accessories',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='sale',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='type_category',
            field=models.CharField(choices=[('CRT', 'Картриджи'), ('MND', 'Мундштуки'), ('IS', 'Испарители'), ('NMK', 'Намотки')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crates',
            name='brand',
            field=models.CharField(default='другие', max_length=255, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='crates',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='crates',
            name='sale',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='liquids',
            name='brand',
            field=models.CharField(default='другие', max_length=255, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='liquids',
            name='country',
            field=models.CharField(default='другие', max_length=255, verbose_name='Страна производитель'),
        ),
        migrations.AddField(
            model_name='liquids',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='liquids',
            name='nicotine',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Содержание никотина'),
        ),
        migrations.AddField(
            model_name='liquids',
            name='sale',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='liquids',
            name='salt',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='SALT'),
        ),
        migrations.AddField(
            model_name='liquids',
            name='taste',
            field=models.CharField(default='другие', max_length=255, verbose_name='Вкус'),
        ),
        migrations.AddField(
            model_name='liquids',
            name='vg_to_pg',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='ВГ на ПГ'),
        ),
        migrations.AddField(
            model_name='liquids',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Объем'),
        ),
    ]
