# Generated by Django 3.1 on 2020-09-06 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200906_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('brand', models.CharField(default='другие', max_length=255, verbose_name='Бренд')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('date', models.DateField(default=datetime.datetime.utcnow, verbose_name='Дата добавления')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Скидка')),
                ('color', models.CharField(default='другие', max_length=100)),
                ('type_category', models.CharField(choices=[('NMK', 'Намотки'), ('IS', 'Испарители'), ('CRT', 'Картриджи'), ('MND', 'Мундштуки')], max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Crates',
            new_name='Crate',
        ),
        migrations.RenameModel(
            old_name='Liquids',
            new_name='Liquid',
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
    ]
