# Generated by Django 3.1 on 2020-10-02 13:21

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201001_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='title_slug',
        ),
        migrations.RemoveField(
            model_name='crate',
            name='title_slug',
        ),
        migrations.RemoveField(
            model_name='liquid',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='liquid',
            name='title_slug',
        ),
        migrations.AddField(
            model_name='accessory',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Добавить в категорию новые?'),
        ),
        migrations.AddField(
            model_name='crate',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Добавить в категорию новые?'),
        ),
        migrations.AddField(
            model_name='liquid',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Добавить в категорию новые?'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 16, 21, 14, 889610), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('MND', 'Мундштуки'), ('NMK', 'Намотки'), ('CRT', 'Картриджи'), ('IS', 'Испарители')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='crate',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 16, 21, 14, 889610), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='crate',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 16, 21, 14, 889610), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='salt',
            field=models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], max_length=255, verbose_name='SALT'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 16, 21, 14, 891593), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 16, 21, 14, 891593), verbose_name='Время добавления'),
        ),
    ]
