# Generated by Django 3.1 on 2020-10-02 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201002_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='color',
        ),
        migrations.AlterField(
            model_name='accessory',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 16, 52, 18, 766607), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('MND', 'Мундштуки'), ('CRT', 'Картриджи'), ('IS', 'Испарители'), ('NMK', 'Намотки')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='crate',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 16, 52, 18, 766607), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 16, 52, 18, 766607), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='salt',
            field=models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], max_length=255, verbose_name='SALT'),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 16, 52, 18, 768573), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 16, 52, 18, 769591), verbose_name='Время добавления'),
        ),
    ]
