# Generated by Django 3.1 on 2020-10-02 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201002_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProduct',
        ),
        migrations.AlterField(
            model_name='accessory',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 19, 46, 5, 73404), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('MND', 'Мундштуки'), ('NMK', 'Намотки'), ('CRT', 'Картриджи'), ('VTA', 'Вата'), ('IS', 'Испарители')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='crate',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 19, 46, 5, 73404), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 19, 46, 5, 73404), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 19, 46, 5, 75399), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 2, 19, 46, 5, 75399), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='table',
            field=models.CharField(choices=[('LQD', 'Liquid'), ('ACC', 'Accessory')], max_length=255, null=True, verbose_name='Категория'),
        ),
    ]
