# Generated by Django 3.1 on 2020-10-03 09:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201003_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='memory_size',
        ),
        migrations.RemoveField(
            model_name='desktop',
            name='storage_size',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='producted',
            name='name',
        ),
        migrations.RemoveField(
            model_name='producted',
            name='stock',
        ),
        migrations.AddField(
            model_name='desktop',
            name='country',
            field=models.CharField(default='другие', max_length=255, verbose_name='Страна производитель'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='nicotine',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Содержание никотина'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='salt',
            field=models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], max_length=255, null=True, verbose_name='SALT'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='taste',
            field=models.CharField(default='другие', max_length=255, verbose_name='Вкус'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='vg_to_pg',
            field=models.CharField(max_length=255, null=True, verbose_name='ВГ на ПГ'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='type_category',
            field=models.CharField(choices=[('CRT', 'Картриджи'), ('IS', 'Испарители'), ('MND', 'Мундштуки'), ('NMK', 'Намотки'), ('VTA', 'Вата')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AddField(
            model_name='producted',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='producted',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 3, 12, 5, 16, 786341), verbose_name='Время добавления'),
        ),
        migrations.AddField(
            model_name='producted',
            name='brand',
            field=models.CharField(default='другие', max_length=255, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='producted',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='producted',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='producted',
            name='image',
            field=models.ImageField(default=90, upload_to='images', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producted',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Добавить в категорию новые?'),
        ),
        migrations.AddField(
            model_name='producted',
            name='sale',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='producted',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='producted',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessory',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 3, 12, 5, 16, 782351), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('CRT', 'Картриджи'), ('IS', 'Испарители'), ('MND', 'Мундштуки'), ('NMK', 'Намотки'), ('VTA', 'Вата')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='crate',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 3, 12, 5, 16, 782351), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 3, 12, 5, 16, 782351), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 3, 12, 5, 16, 785347), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='producted',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='producted',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 3, 12, 5, 16, 785347), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='table',
            field=models.CharField(choices=[('Liquid', 'Liquid'), ('Accessory', 'Accessory')], max_length=255, null=True, verbose_name='Категория'),
        ),
    ]
