# Generated by Django 3.1 on 2020-10-03 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201003_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('IS', 'Испарители'), ('NMK', 'Намотки'), ('CRT', 'Картриджи'), ('VTA', 'Вата'), ('MND', 'Мундштуки')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 4, 1, 11, 22, 528442), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 4, 1, 11, 22, 525464), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 4, 1, 11, 22, 527425), verbose_name='Время добавления'),
        ),
    ]
