# Generated by Django 3.1 on 2020-10-10 18:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201005_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'Другое',
                'verbose_name_plural': 'Другое',
            },
            bases=('products.product',),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('namotki', 'Намотки'), ('kartridzh', 'Картриджи'), ('vata', 'Вата'), ('isparitel', 'Испарители'), ('mundshtuki', 'Мундштуки')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='salt',
            field=models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], max_length=255, null=True, verbose_name='SALT'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 10, 21, 23, 22, 33155), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 10, 21, 23, 22, 30516), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 10, 21, 23, 22, 32578), verbose_name='Время добавления'),
        ),
        migrations.DeleteModel(
            name='Categor',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
