# Generated by Django 3.1 on 2020-10-10 19:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20201010_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('liquid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.liquid')),
            ],
            options={
                'verbose_name': 'Cloud',
                'verbose_name_plural': 'Cloud',
            },
            bases=('products.liquid',),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('isparitel', 'Испарители'), ('kartridzh', 'Картриджи'), ('vata', 'Вата'), ('namotki', 'Намотки'), ('mundshtuki', 'Мундштуки')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='salt',
            field=models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=255, null=True, verbose_name='SALT'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 10, 22, 34, 55, 604774), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 10, 22, 34, 55, 601783), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 10, 22, 34, 55, 603805), verbose_name='Время добавления'),
        ),
    ]
