# Generated by Django 3.1 on 2020-10-14 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20201011_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('vata', 'Вата'), ('mundshtuki', 'Мундштуки'), ('isparitel', 'Испарители'), ('kartridzh', 'Картриджи'), ('namotki', 'Намотки')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 14, 8, 55, 52, 200809), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 14, 8, 55, 52, 196294), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 14, 8, 55, 52, 199451), verbose_name='Время добавления'),
        ),
    ]
