# Generated by Django 3.1 on 2020-10-17 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20201017_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('namotki', 'Намотки'), ('mundshtuki', 'Мундштуки'), ('kartridzh', 'Картриджи'), ('isparitel', 'Испарители'), ('vata', 'Вата')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 17, 22, 28, 36, 79337), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 17, 22, 28, 36, 74840), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 17, 22, 28, 36, 78535), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='table',
            field=models.CharField(choices=[('Accessory', 'Accessory'), ('Liquid', 'Liquid')], max_length=255, null=True, verbose_name='Категория'),
        ),
    ]
