# Generated by Django 3.1 on 2020-10-18 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20201018_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('namotki', 'Намотки'), ('kartridzh', 'Картриджи'), ('mundshtuki', 'Мундштуки'), ('isparitel', 'Испарители'), ('vata', 'Вата')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='salt',
            field=models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], max_length=255, null=True, verbose_name='SALT'),
        ),
        migrations.AlterField(
            model_name='liquid',
            name='volume',
            field=models.PositiveIntegerField(null=True, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 18, 8, 54, 53, 743258), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 18, 8, 54, 53, 738412), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 18, 8, 54, 53, 742357), verbose_name='Время добавления'),
        ),
    ]
