# Generated by Django 3.1 on 2020-10-18 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20201018_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('kartridzh', 'Картриджи'), ('namotki', 'Намотки'), ('isparitel', 'Испарители'), ('mundshtuki', 'Мундштуки'), ('vata', 'Вата')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 18, 19, 22, 34, 288494), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 18, 19, 22, 34, 283910), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 18, 19, 22, 34, 287644), verbose_name='Время добавления'),
        ),
    ]
