# Generated by Django 3.1 on 2020-10-18 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20201018_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('mundshtuki', 'Мундштуки'), ('namotki', 'Намотки'), ('kartridzh', 'Картриджи'), ('vata', 'Вата'), ('isparitel', 'Испарители')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 18, 21, 44, 54, 732882), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 18, 21, 44, 54, 727658), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 18, 21, 44, 54, 731939), verbose_name='Время добавления'),
        ),
    ]
