# Generated by Django 3.1 on 2020-10-19 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20201019_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='type_category',
            field=models.CharField(choices=[('isparitel', 'Испарители'), ('namotki', 'Намотки'), ('vata', 'Вата'), ('kartridzh', 'Картриджи'), ('mundshtuki', 'Мундштуки')], max_length=255, null=True, verbose_name='Подтверди название категории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 19, 16, 56, 2, 398746), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 19, 16, 56, 2, 394564), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images', verbose_name='Изображение-2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images', verbose_name='Изображение-3'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='add_time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 19, 16, 56, 2, 397961), verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='table',
            field=models.CharField(choices=[('Accessory', 'Accessory'), ('Liquid', 'Liquid')], max_length=255, null=True, verbose_name='Категория'),
        ),
    ]
